version: "3.9"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Igor1234!
      MYSQL_DATABASE: school
      MYSQL_USER: root
      MYSQL_PASSWORD: Igor1234!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - schoolnet

  api-horarios:
    build: .
    container_name: api-horarios
    restart: always
    depends_on:
      - mysql-db
    environment:
      DB_HOST: mysql-db
      DB_USER: root
      DB_PASSWORD: Igor1234!
      DB_NAME: school
    ports:
      - "8080:8080"
    networks:
      - schoolnet

volumes:
  mysql_data:

networks:
  schoolnet:
